name: WebNotify
on:
 # schedule:
 #    - cron: 0 * * * *

  workflow_dispatch:

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: webnotify
        uses: laddge/webnotify@v3
        with:
          targets: ${{secrets.TARGETS}}
          line_token: ${{secrets.LINE_TOKEN}}
          timezone: Asia/Tokyo
